In [1]:
name = 'rafee'

In [2]:
capitalisedName = name.capitalize()

In [3]:
print(capitalisedName)

Rafee


In [4]:
firstCharName = name[0]
print(firstCharName)

r


In [5]:
lastCharName = name[-1]
print(lastCharName)

e


In [7]:
nameExceptFirstChar = name[1:]
print(nameExceptFirstChar)

afee


In [8]:
everyOtherChar = name[::2]
print(everyOtherChar)

rfe


In [10]:
twoCopiesOfName = name + name
print("Two copies of Name: ", twoCopiesOfName)

Two copies of Name:  rafeerafee


In [11]:
ages = [92,90,94,95,97,96,98,21,94,92,95,97,92,97,98]

In [12]:
len(ages)

15

In [18]:
def displayFirstAndLast(list):
    return print('first: ',list[0], 'last: ', list[-1])

In [19]:
displayFirstAndLast(ages)

first:  92 last:  98


In [20]:
def thirdToLastElement(list):
    return print('third to last slide: ', list[2:])

In [21]:
thirdToLastElement(ages)

third to last slide:  [94, 95, 97, 96, 98, 21, 94, 92, 95, 97, 92, 97, 98]


In [29]:
def printList(list):
    for age in list:
        print('Index position: ', list.index(age) , 'Age: ', age)

In [30]:
printList(ages)

Index position:  0 Age:  92
Index position:  1 Age:  90
Index position:  2 Age:  94
Index position:  3 Age:  95
Index position:  4 Age:  97
Index position:  5 Age:  96
Index position:  6 Age:  98
Index position:  7 Age:  21
Index position:  2 Age:  94
Index position:  0 Age:  92
Index position:  3 Age:  95
Index position:  4 Age:  97
Index position:  0 Age:  92
Index position:  4 Age:  97
Index position:  6 Age:  98


In [33]:
ThomasHolmesGuess = 95
ages.append(ThomasHolmesGuess)
print('new list length: ', len(ages))
print(ages)
printList(ages)

new list length:  18
[92, 90, 94, 95, 97, 96, 98, 21, 94, 92, 95, 97, 92, 97, 98, 95, 95, 95]
Index position:  0 Age:  92
Index position:  1 Age:  90
Index position:  2 Age:  94
Index position:  3 Age:  95
Index position:  4 Age:  97
Index position:  5 Age:  96
Index position:  6 Age:  98
Index position:  7 Age:  21
Index position:  2 Age:  94
Index position:  0 Age:  92
Index position:  3 Age:  95
Index position:  4 Age:  97
Index position:  0 Age:  92
Index position:  4 Age:  97
Index position:  6 Age:  98
Index position:  3 Age:  95
Index position:  3 Age:  95
Index position:  3 Age:  95


**Practical Dictionaries**

In [34]:
books = {
    "title": "Hamlet",
    "author": "William Shakespeare",
    "language": "English",
}

In [35]:
books['title']

'Hamlet'

In [37]:
books.keys()

dict_keys(['title', 'author', 'language'])

In [38]:
books.values()

dict_values(['Hamlet', 'William Shakespeare', 'English'])

In [39]:
books.items()

dict_items([('title', 'Hamlet'), ('author', 'William Shakespeare'), ('language', 'English')])

In [40]:
books['title'] = 'King Lear'

In [41]:
books

{'title': 'King Lear', 'author': 'William Shakespeare', 'language': 'English'}

**Practical: Selection**

In [44]:
age = int(input('Please enter your age: '))

if age >= 18:
    print('You are in category A')
elif age >= 16:
    print('You are in category B')
elif age < 16:
    print('You are in category C')

Please enter your age: 19
You are in category A


**Practical Numpy exercise**

In [45]:
import numpy as np

In [46]:
payments = np.array([6.99, 12.40, 75.00, 1.55])

In [47]:
payments

array([ 6.99, 12.4 , 75.  ,  1.55])

In [49]:
arr = np.array([1,3,5,7,9])

arr2 = np.array([[1,3,5,7], [2,4,6,8]])

print(arr2)

[[1 3 5 7]
 [2 4 6 8]]


In [50]:
payments[payments < 10]

array([6.99, 1.55])

In [51]:
payments

array([ 6.99, 12.4 , 75.  ,  1.55])

In [52]:
payments.sum()

95.94